name: "Deploy (staff)"

on:
    # Run on every push to main that changes web/apps/staff/
    push:
        branches: [main]
        paths:
            - "web/apps/staff/**"
            - ".github/workflows/web-deploy-staff.yml"
    # Also allow manually running the workflow
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: web

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Setup node and enable yarn caching
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "yarn"
                  cache-dependency-path: "web/yarn.lock"

            - name: Install dependencies
              run: yarn install

            - name: Build staff
              run: yarn build:staff

            - name: Publish staff
              uses: cloudflare/pages-action@1
              with:
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  projectName: ente
                  branch: deploy/staff
                  directory: web/apps/staff/dist
                  wranglerVersion: "3"
